// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	migrator "github.com/adharshmk96/stk/pkg/migrator"
	mock "github.com/stretchr/testify/mock"
)

// DatabaseRepo is an autogenerated mock type for the DatabaseRepo type
type DatabaseRepo struct {
	mock.Mock
}

// ApplyMigration provides a mock function with given fields: migration
func (_m *DatabaseRepo) ApplyMigration(migration *migrator.MigrationWithQuery) error {
	ret := _m.Called(migration)

	var r0 error
	if rf, ok := ret.Get(0).(func(*migrator.MigrationWithQuery) error); ok {
		r0 = rf(migration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMigrationTableIfNotExists provides a mock function with given fields:
func (_m *DatabaseRepo) CreateMigrationTableIfNotExists() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteMigrationTable provides a mock function with given fields:
func (_m *DatabaseRepo) DeleteMigrationTable() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLastAppliedMigration provides a mock function with given fields:
func (_m *DatabaseRepo) GetLastAppliedMigration() (*migrator.MigrationEntry, error) {
	ret := _m.Called()

	var r0 *migrator.MigrationEntry
	var r1 error
	if rf, ok := ret.Get(0).(func() (*migrator.MigrationEntry, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *migrator.MigrationEntry); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*migrator.MigrationEntry)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMigrationEntries provides a mock function with given fields:
func (_m *DatabaseRepo) GetMigrationEntries() (*[]migrator.MigrationEntry, error) {
	ret := _m.Called()

	var r0 *[]migrator.MigrationEntry
	var r1 error
	if rf, ok := ret.Get(0).(func() (*[]migrator.MigrationEntry, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *[]migrator.MigrationEntry); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]migrator.MigrationEntry)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDatabaseRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewDatabaseRepo creates a new instance of DatabaseRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDatabaseRepo(t mockConstructorTestingTNewDatabaseRepo) *DatabaseRepo {
	mock := &DatabaseRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
