// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	sqlmigrator "github.com/adharshmk96/stk/pkg/sqlMigrator"
	mock "github.com/stretchr/testify/mock"
)

// DBRepo is an autogenerated mock type for the DBRepo type
type DBRepo struct {
	mock.Mock
}

// DeleteMigrationTable provides a mock function with given fields:
func (_m *DBRepo) DeleteMigrationTable() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exec provides a mock function with given fields: query
func (_m *DBRepo) Exec(query string) error {
	ret := _m.Called(query)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(query)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InitMigrationTable provides a mock function with given fields:
func (_m *DBRepo) InitMigrationTable() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadHistory provides a mock function with given fields:
func (_m *DBRepo) LoadHistory() ([]*sqlmigrator.MigrationDBEntry, error) {
	ret := _m.Called()

	var r0 []*sqlmigrator.MigrationDBEntry
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*sqlmigrator.MigrationDBEntry, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*sqlmigrator.MigrationDBEntry); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sqlmigrator.MigrationDBEntry)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PushHistory provides a mock function with given fields: migration
func (_m *DBRepo) PushHistory(migration *sqlmigrator.MigrationDBEntry) error {
	ret := _m.Called(migration)

	var r0 error
	if rf, ok := ret.Get(0).(func(*sqlmigrator.MigrationDBEntry) error); ok {
		r0 = rf(migration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDBRepo creates a new instance of DBRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBRepo {
	mock := &DBRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
