// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gsk "github.com/adharshmk96/stk/gsk"
	mock "github.com/stretchr/testify/mock"
)

// HandlerFunc is an autogenerated mock type for the HandlerFunc type
type HandlerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *HandlerFunc) Execute(_a0 *gsk.Context) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewHandlerFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewHandlerFunc creates a new instance of HandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHandlerFunc(t mockConstructorTestingTNewHandlerFunc) *HandlerFunc {
	mock := &HandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
