// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PingStorage is an autogenerated mock type for the PingStorage type
type PingStorage struct {
	mock.Mock
}

// Ping provides a mock function with given fields:
func (_m *PingStorage) Ping() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPingStorage interface {
	mock.TestingT
	Cleanup(func())
}

// NewPingStorage creates a new instance of PingStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPingStorage(t mockConstructorTestingTNewPingStorage) *PingStorage {
	mock := &PingStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
