// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gsk "github.com/adharshmk96/stk/gsk"
	mock "github.com/stretchr/testify/mock"
)

// PingHandlers is an autogenerated mock type for the PingHandlers type
type PingHandlers struct {
	mock.Mock
}

// PingHandler provides a mock function with given fields: gc
func (_m *PingHandlers) PingHandler(gc *gsk.Context) {
	_m.Called(gc)
}

type mockConstructorTestingTNewPingHandlers interface {
	mock.TestingT
	Cleanup(func())
}

// NewPingHandlers creates a new instance of PingHandlers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPingHandlers(t mockConstructorTestingTNewPingHandlers) *PingHandlers {
	mock := &PingHandlers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
